#!/usr/bin/env python3

import webbrowser
from os import system
from time import sleep
from random import randint

alle_spørsmål = {}
poeng = 0

with open("spørsmål.txt", "r") as fil:
    linjer = fil.readlines()
    for linje in linjer:
        spørsmål, svar = linje.split(":") 
        spørsmål = spørsmål.strip()
        svar = svar.strip().lower()
        alle_spørsmål[spørsmål] = svar


antall = len(alle_spørsmål)

for spørsmål, svar in alle_spørsmål.items():
    print(spørsmål)
    ditt_svar = input(str("Skriv svaret: ")).lower().strip()
    if svar == ditt_svar:
        print("Riktig svar!")
        poeng += 1
        sleep(2)
        continue

    print("feil")
    random = randint(1,3)
    if random == 1:
        system("mpv rick_roll.mkv") 
    sleep(2)

print(f"Poeng: {poeng} av {antall} mulige")
