# Generated by Django 3.1.4 on 2021-01-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210113_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='temporary',
            field=models.BooleanField(default=False),
        ),
    ]
