# Generated by Django 3.1.4 on 2021-01-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_player_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(default='tempuser', max_length=100),
        ),
    ]
