# Generated by Django 3.1.4 on 2021-01-18 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210115_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizark',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
